apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakehouse
  labels:
    app.kubernetes.io/name: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lakehouse
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lakehouse
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
      - name: lakehouse-db-volume
        persistentVolumeClaim:
          claimName: lakehouse-db-volume-pvc
      containers:
      - name: lakehouse
        image: cuebook/lakehouse:latest
        volumeMounts:
        - name: lakehouse-db-volume     # configure this to persist db
          mountPath: /code/db
        envFrom:
        - configMapRef:
            name: cuelake-conf-map
        ports:
        - name: http
          containerPort: 80