apiVersion: v1
kind: ServiceAccount
metadata:
  name: cuelake
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cuelake-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "services", "configmaps"]
  verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cuelake-role-binding
subjects:
- kind: ServiceAccount
  name: cuelake
roleRef:
  kind: Role
  name: cuelake-role
  apiGroup: rbac.authorization.k8s.io