apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakehouse
  labels:
    app.kubernetes.io/name: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lakehouse
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lakehouse
    spec:
      serviceAccountName: cuelake
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
      - name: lakehouse-db-volume
        persistentVolumeClaim:
          claimName: lakehouse-db-volume-pvc
      containers:
      - name: lakehouse
        image: cuebook/lakehouse:0.3
        resources:
          requests:
            memory: "2560Mi"
            cpu: "250m"
        volumeMounts:
        - name: lakehouse-db-volume     # configure this to persist db
          mountPath: /code/db
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: cuelake-conf-map
        ports:
        - name: http
          containerPort: 80