kind: Service
apiVersion: v1
metadata:
  name: sparkui
spec:
  ports:
    - name: spark-ui
      protocol: TCP
      port: 4040
      targetPort: 4040
  selector:
    interpreterSettingName: spark
  type: ClusterIP
  sessionAffinity: None