kind: Service
apiVersion: v1
metadata:
  name: zeppelin-server
spec:
  ports:
    - name: http
      port: 80
    - name: rpc
      port: 12320
  selector:
    app.kubernetes.io/name: zeppelin-server-main